### ISSUE TITLE
Matterport3D dataset

### ISSUE THREAD

**Issue by newofboy** [caozidong/CRF360D#1]
Hello, regarding the Matterport3D dataset, I downloaded a total of 9684 pairs of images and depths from the official website, but there is a significant difference between the segmentation files you provided (7829+2014+957). Can you tell me how your data was processed

**Comment by caozidong** [comment]
Hi, can you provide the details about where you download the dataset? I download the raw files (perspective images) from Matterport3D, and manually stitch them into panoramas. The split files are consistent with UniFuse.
